#!/bin/bash

# Result will be output in place of the default commit message on running git commit
current_branch=`git rev-parse --abbrev-ref HEAD`

echo "##############################################################################################"
echo "##"
echo "#$current_branch Commit messages should be of the form"
echo "#[CurrentSprint:TaskID] Commit Message." > $1
echo "##"
echo "##############################################################################################"
echo \n
